on:
  push:
    paths:
      - src/**
    branches:
      - main
  workflow_dispatch:

name: Build and Release Policy Repo

jobs:
  release_repo:
    name: Release Repo
    uses: wso2-cicd/wso2-workflows/.github/workflows/release-apim-policy.yml@main
    secrets: inherit